### ISSUE TITLE
Query regarding matrix calculation

### ISSUE THREAD

**Issue by dev-aritra** [eh3rrera/ARKitCarGeolocation#1]
Firstly, thanks a ton for developing this solution and providing the tutorial, it has been an extremely helpful resource.

I understood what you mentioned about bearing and distance, but could not understand what's up with all those matrix calculations.
Can you please explain what actually happened there, or if you have any existing resource to back that up, that will be awesome too.

**Comment by eh3rrera** [comment]
Hi Aritra,

In 3D programming, matrices are used to represent graphical transformations like translation, scaling, rotation, and projection. Through matrix multiplication, multiple transformations can be concatenated into a single transformation matrix.

Before writing the tutorial for this app, I wrote a couple of tutorials where I explained in more detail matrix operations. For example:
https://blog.pusher.com/building-ar-game-arkit-spritekit/

You can search for something like "3d matrix transformation", there's a lot of information. Here are some links to get you started:
https://web.archive.org/web/20180829224547/http://ronnqvi.st/the-math-behind-transforms/
http://www.opengl-tutorial.org/beginners-tutorials/tutorial-3-matrices/
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/CoreAnimationBasics/CoreAnimationBasics.html#//apple_ref/doc/uid/TP40004514-CH2-SW18

Hope it helps!
